Tip messages
BootGen/VueStart pull request #13
Opened 2022-01-06 15:23 UTC by echopot

2022-01-07 10:03 UTC, agabor commented
1. A generálásnál is legyen success vuecoon
2. A tipp animálva változzon (eltűnik majd megjelenik)

2022-01-07 13:40 UTC, echopot commented
> 1. A generálásnál is legyen success vuecoon
> 2. A tipp animálva változzon (eltűnik majd megjelenik)
198e89fffdbf5534d4f1547384c826546ac98702
b4ca7722163074892f7d560b57e049b1965a9700

2022-01-10 13:40 UTC, agabor requested changes

2022-01-10 13:40 UTC, agabor commented on ClientApp/src/App.vue
> +    }
Nem szép, hogy többször egymás után meghívod a `localStorage.getItem('showTips')`-et. Mentsd el változóba!

2022-01-10 13:40 UTC, agabor commented on ClientApp/src/App.vue
> +    }
A `firstUse`, `regeneratedTip` és `buttonsTip ` helyett használj inkább egy tipIndex értéket!

2022-01-12 14:53 UTC, merged